import './globals.css'
import "react-datepicker/dist/react-datepicker.css";
import { Kanit } from 'next/font/google'
import type { Metadata } from 'next'
import { LayoutContextProvider } from '@/contexts/layout'
import { DataContextProvider } from '@/contexts/data';

const kanit = Kanit({
  subsets: ['thai'],
  display: 'fallback',
  weight: '300',
})

export const metadata: Metadata = {
  title: 'Skytrain Ticket Booking',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <link rel="icon" href="/next.svg" />
      <body suppressHydrationWarning className={kanit.className}>
        <DataContextProvider>
        <LayoutContextProvider>{children}</LayoutContextProvider>
        </DataContextProvider>
      </body>
    </html>
  )
}
